---
# File: roles/zaproxy/vars/main.yml
# https://github.com/zaproxy/zaproxy/releases/download/2.4.3/ZAP_2.4.3_Linux.tar.gz
# https://github.com/zaproxy/zaproxy/releases/download/2.4.3/ZAP_2.4.3_Linux.tar.gz

zaproxy_version: 2.4.3

zaproxy_host: https://github.com
zaproxy_path: /zaproxy/zaproxy/releases/download/{{ zaproxy_version }}
zaproxy_file: ZAP_{{ zaproxy_version }}_Linux.tar.gz

zaproxy_url: "{{ zaproxy_host }}/{{ zaproxy_path }}/{{ zaproxy_file }}"

zaproxy_installation_directory: /opt/zaproxy
zaproxy_tar_directory: "{{ zaproxy_installation_directory }}/ZAP_{{ zaproxy_version }}"
zaproxy_home_directory: "{{ zaproxy_installation_directory }}/{{ zaproxy_version }}"
