---
# File: /roles/eclipse/vars/main.yml

# https://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/2021-06/R/eclipse-java-2021-06-R-linux-gtk-x86_64.tar.gz

eclipse_release: "{{ eclipse_version }}-{{ eclipse_sr }}"

eclipse_host: https://ftp.osuosl.org
eclipse_path: pub/eclipse/technology/epp/downloads/release/{{ eclipse_version }}/{{ eclipse_sr }}
eclipse_file_32: eclipse-jee-{{ eclipse_release }}-linux-gtk.tar.gz
eclipse_file_64: eclipse-jee-{{ eclipse_release }}-linux-gtk-x86_64.tar.gz

eclipse_url_32: "{{ eclipse_host }}/{{ eclipse_path }}/{{ eclipse_file_32 }}"
eclipse_url_64: "{{ eclipse_host }}/{{ eclipse_path }}/{{ eclipse_file_64 }}"

eclipse_installation_directory: /opt/eclipse
eclipse_tar_directory: "{{ eclipse_installation_directory }}/eclipse"
eclipse_home_directory: "{{ eclipse_installation_directory }}/{{ eclipse_release }}"


lombok_host: https://repo.maven.apache.org
lombok_path: maven2/org/projectlombok/lombok/{{ lombok_version }}
lombok_file: lombok-{{ lombok_version }}.jar

lombok_url: "{{ lombok_host }}/{{ lombok_path }}/{{ lombok_file }}"


eclim_host: https://github.com
eclim_path: ervandew/eclim/releases/download/{{ eclim_version }}
eclim_file: eclim_{{ eclim_version }}.bin

eclim_url: "{{ eclim_host }}/{{ eclim_path }}/{{ eclim_file }}"

