---
# File: /roles/eclipse/vars/main.yml
# http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/neon/1a/eclipse-reporting-neon-1a-linux-gtk-x86_64.tar.gz
# http://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/oxygen/M5/eclipse-jee-oxygen-M5-linux-gtk-x86_64.tar.gz

#eclipse_version: neon
#eclipse_sr: 2

eclipse_version: oxygen
eclipse_sr: M5

eclipse_release: "{{ eclipse_version }}-{{ eclipse_sr }}"

eclipse_host: http://mirror.cc.columbia.edu
eclipse_path: pub/software/eclipse/technology/epp/downloads/release/{{ eclipse_version }}/{{ eclipse_sr }}
eclipse_file_32: eclipse-reporting-{{ eclipse_release }}-linux-gtk.tar.gz
eclipse_file_64: eclipse-reporting-{{ eclipse_release }}-linux-gtk-x86_64.tar.gz

eclipse_url_32: "{{ eclipse_host }}/{{ eclipse_path }}/{{ eclipse_file_32 }}"
eclipse_url_64: "{{ eclipse_host }}/{{ eclipse_path }}/{{ eclipse_file_64 }}"

eclipse_installation_directory: /opt/eclipse
eclipse_tar_directory: "{{ eclipse_installation_directory }}/eclipse"
eclipse_home_directory: "{{ eclipse_installation_directory }}/{{ eclipse_release }}"




lombok_version: 1.16.14

lombok_host: https://repo.maven.apache.org
lombok_path: maven2/org/projectlombok/lombok/{{ lombok_version }}
lombok_file: lombok-{{ lombok_version }}.jar

lombok_url: "{{ lombok_host }}/{{ lombok_path }}/{{ lombok_file }}"




eclim_version: 2.6.0

eclim_host: https://github.com
eclim_path: ervandew/eclim/releases/download/{{ eclim_version }}
eclim_file: eclim_{{ eclim_version }}.jar

eclim_url: "{{ eclim_host }}/{{ eclim_path }}/{{ eclim_file }}"

