---
# File: roles/firefox_de/vars/main.yml
# https://download-installer.cdn.mozilla.net/pub/devedition/releases/55.0b2/linux-x86_64/en-US/firefox-55.0b2.tar.bz2
# https://download-installer.cdn.mozilla.net/pub/devedition/releases/55.0b3/linux-x86_64/en-US/firefox-55.0b3.tar.bz2
# https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US

firefox_de_version: 56.0b6
firefox_de_language: en-US

firefox_de_host: https://download-installer.cdn.mozilla.net
firefox_de_path_32: pub/devedition/releases/{{ firefox_de_version }}/linux-i686/en-US
firefox_de_path_64: pub/devedition/releases/{{ firefox_de_version }}/linux-x86_64/en-US
firefox_de_file: firefox-{{ firefox_de_version }}.tar.bz2

firefox_de_url_32: "{{ firefox_de_host }}/{{ firefox_de_path_32 }}/{{ firefox_de_file }}"
firefox_de_url_64: "{{ firefox_de_host }}/{{ firefox_de_path_64 }}/{{ firefox_de_file }}"

firefox_de_installation_directory: /opt/firefox-de
firefox_de_tar_directory: "{{ firefox_de_installation_directory }}/firefox"
firefox_de_home_directory: "{{ firefox_de_installation_directory }}/{{ firefox_de_version }}"
