---
# roles/burp_suite/vars/main.yml
# https://portswigger.net/DownloadUpdate.ashx?Product=Free

burp_version: latest

burp_url: https://portswigger.net/DownloadUpdate.ashx?Product=Free

burp_file: burpsuite_free_{{ burp_version }}.jar

burp_installation_directory: /opt/burpsuite/{{ burp_version }}

burp_icon_path: resources/Media
burp_icon_file: icon64.png
